import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'
import './globals.css'

const ubuntu = Ubuntu({
    subsets: ['latin'],
    variable: '--font-ubuntu',
    weight: ["300", "400", "500", "700"]
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by crea2te next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en"  >
            <body className={`${ubuntu.className} bg-zinc-800`}>{children}</body>
        </html >
    )
}
